name: golangci-lint
on: push
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17.8'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.47
          args: --timeout=3m
      - name: install nosnakecase
        run: go install github.com/sivchari/nosnakecase/cmd/nosnakecase@latest

      - name: run nosnakecase
        run: go vet -vettool=`which nosnakecase` ./...